### ISSUE TITLE
Messages - zaimplementować odczytanie

### ISSUE THREAD

**Issue by LetItRock** [grapehacks/parkify-androidapp#1]
1. LoginActivity - do LoginPresenterImpl, PingPresenterImpl przekazać Application.
   <br />2. LoginPresenterImpl, PingPresenterImpl - jest zwracany obiekt UserDto/PingDto z niego trzeba pobrać użytkownika i odczytać ilość nie przeczytanych wiadomości. Tą ilość nie przeczytanych wiadomości zapisać do shared preferences wykorzystując UserDataHelper klassę. 
   <br />3. MessageFragment.onCreateView() - do prezentera przekazać ilość nie przeczytanych wiadomości (skrót INPW) (zrobić tak samo jak z tokenem).
   <br />4. MessagesPresenterImpl.start() - przekazać INPW tak samo jak token
   <br />5. MessagesModelImpl ustawić na endpoincie INPW tak samo jak token
   <br />6. MessagesEndpoint - interceptor - httpBuilder.setEncodedQueryParameter
   <br />7. MessagesPresenterImpl.start() - onNext - zapisać ilość message do shared preferences

**Comment by LetItRock** [comment]
Nie przeczytane wiadomości wyświetlać na liście z lekko zielonym backgroundem, po przeczytaniu zmieniać na biały. Pewnie lepiej będzie nie usuwać z listy.

**Comment by pgasior** [comment]
3c5ada03b1297c762f6831cbd14680f284bb7eb9

**Comment by LetItRock** [comment]
Działa.
